# Generated by Django 4.1.5 on 2023-11-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('person_surname', models.CharField(max_length=30)),
                ('person_firstname', models.CharField(max_length=100)),
                ('person_middlename', models.CharField(max_length=30, null=True)),
                ('person_extension', models.CharField(max_length=5, null=True)),
                ('person_street_no', models.IntegerField()),
                ('person_house_no', models.CharField(max_length=5, null=True)),
                ('person_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('history_timestamp', models.DateTimeField()),
                ('history_short_desc', models.CharField(max_length=100)),
                ('history_long_desc', models.CharField(max_length=1000)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterlist.person')),
            ],
        ),
    ]
