# Generated by Django 4.1.5 on 2023-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0002_alter_history_history_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_done_by',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
