# Generated by Django 4.1.5 on 2023-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0003_history_history_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_long_desc',
            field=models.TextField(),
        ),
    ]
