# Generated by Django 4.1.5 on 2023-12-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlist', '0004_alter_history_history_long_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_done_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
